server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/banking_accounts

services:
  customer:
    base-url: ${CUSTOMER_SERVICE_URL:http://localhost:8081}
  credit:
    base-url: ${CREDIT_SERVICE_URL:http://localhost:8083}

account:
  checking:
    maintenance-fee: 10.00
  savings:
    monthly-movement-limit: 5
  opening:
    minimum-amount: 0
  transactions:
    free-monthly: 5
    commission-fee: 2.50
  vip:
    min-daily-average: 500.00
  pyme:
    maintenance-fee: 0

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.bank.account: DEBUG
