server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/banking_credits

services:
  customer:
    base-url: http://localhost:8081

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.bank.credit: DEBUG
