server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/banking_customers

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.bank.customer: DEBUG
